[project]
name = "model-distillation"
version = "0.1.0"
description = ""
authors = [
    {name = "shevchenkokk",email = "kirill_07_02@mail.ru"}
]
readme = "README.md"
requires-python = "3.13"
dependencies = [
    "torch (>=2.10.0,<3.0.0)",
    "psutil (>=7.2.2,<8.0.0)",
    "transformers (>=5.0.0,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
